/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Main: typeof import('./src/app/components/main/components/main')['Main']
  const app: typeof import('./src/app/app')['default']
  const createRef: typeof import('react')['createRef']
  const first: typeof import('./src/app/components/main/components/additionalContent/first/first')['default']
  const footer: typeof import('./src/app/components/footer/components/footer')['default']
  const forwardRef: typeof import('react')['forwardRef']
  const header: typeof import('./src/app/components/head/components/header')['default']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const second: typeof import('./src/app/components/main/components/additionalContent/second/second')['default']
  const startTransition: typeof import('react')['startTransition']
  const third: typeof import('./src/app/components/main/components/additionalContent/third/third')['default']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { State, Props } from './src/app/components/main/components/main'
  import('./src/app/components/main/components/main')
}
